# What is Python?

It is an interpreted high-level programming language. It is available at https://www.python.org/.

Python itself does not provide many features. It can be enriched by additional libraries.

For our purposes, following libraries are commonly used:
* numpy (http://www.numpy.org/), for scientific computing on arrays of number
* pandas (http://pandas.pydata.org/), to deal with mixed data (text and numerical data) easily.
* matplotlib (https://matplotlib.org/), to plot data and produce figures for reports and presentations.

Python and its libraries are often updated, and it can be hard to manage compatibility between multiple libraries and your version of Python. It can be more convenient to install Anaconda, which can manage you Python environment automatically (https://www.anaconda.com/).


# How to use it?

As an interpreted language, it demands an interpreter. The basic interpreter can be launched with the command (in a terminal) "python".

![python_basic_interpreter.png](./figures/python_basic_interpreter.png "intepréteur python")

You can also run a script, for instance "myPythonScript.py", with the command "python myPythonScript.py".
To develop your code, you may need a more interactive way of programming. You can use the library *IPython*, and the more advanced (and complex) *jupyter-notebook*, based on IPython. These tools add many functionalities to make your development easier.
![intepréteur ipython.png](./figures/Ipython.png "intepréteur ipython")

# Jupyter basics

Jupyter-notebook is a graphical interface, based on Ipython, to make script prototypes and interactive presentation. A jupyter-notebook opens in web navigator, and can be exported in pdf, python script file, etc. It should not be used for complex codes and when dealing with massive amount of data.

A notebook is composed of cells. A cell can contain code or text. To see what's behind the cell you are reading, you can double-click on it, or you can navigate the notebook with keyboard's arrows and type Enter on the cell.

Basic commands to use the jupyter-notebook :
- Edit a cell : Enter (left side of the cell is green)
- Run a cell : Shift (hold) + Enter
- See the documentation of a function (when cursor is on the name of the function) : Shift (hold) + Tab + Tab.
- Delete a cell : escape + d + d
- save your notebook: ctrl + s

You can have a look on all commands in Help (see top bar of the window).

Be careful! You can select and run a cell, in any order you want. This may cause weird behavior if you do not respect the order of cell. To be sure your code behaves well, click on *kernel* button, and on *Restart and clear output*.

# Python basics

### Definition of variables

In [ ]:
a = 1
b = 1.
c = 1 + 2 * 1j
d = 'variables'

### Add comments

In [ ]:
a = 1
# The following instruction is commented
#a = 2
print(a)

### Check variable

In [ ]:
print('The variable a is a {} and its value is {}'.format(a,type(a)))

In [ ]:
# Lists
a = [1, 2, 3, 4, 5]
b = [] # Empty list, useful to initiate it and to fill it later.
c = [element for element in range(3)]
d = [[1, 2], [1, 2]]

In [ ]:
print('First element of a = {}'.format(a[0]))
print('Last element of a = {}'.format(a[-1])) # Pour l'avant-dernier : a[-2]
print('Two first elements of a = {}'.format(a[:2])) # ou a[0:2]
print('2 by 2 :{}'.format(a[::2]))
print('Reverse order of a :{}'.format(a[::-1]))
print('First element of d = {}'.format(d[0]))
print('Second element of the first element of d = {}'.format(d[0][1]))

In [ ]:
# Dictionnary
a = {'Stress' : 35,
     'Unit' : 'MPa'}

b = dict(Stress = 35, Unit = 'MPa')
print('a = {}'.format(a))
print('b = {}'.format(b))

In [ ]:
a['Stress'] = a['Stress'] * 1e6
a['Unit'] = 'Pa'

print('a = {}'.format(a))
print('b = {}'.format(b))

### Conditional structure

In [ ]:
variable = 1

if variable == 1:
    print('Good Morning')
elif variable == 2:
    print('Good Evening')
else:
    print('Good Night')

### Loops (for and while)

In [ ]:
# be careful, indentation is meaningful
for i in range(2, 10, 1):
    a = 2 * i
    b = a + i
    print('(2 x {}) + {} = {}'.format(i,i,b))

In [ ]:
variable = [i for i in range(10) if not i % 2]
print('variable = {}'.format(variable))
print('type de variable : {}'.format(type(variable)))

In [ ]:
liste = ['Hello', 'How are you doing ?', 'Ok nice, see you later then !']
for string in liste:
    print(string)

In [ ]:
i = 0
while i < 2:
    print('hello World')
    i += 1 # This is a comment
    # i += 1 means i + 1

### Operation on numerical data

In [ ]:
# addition
addition = 3 + 2
addition_float = 3. + 2.

print(addition, addition_float)

# multiplication and division
multip = 3 * 2
division = 3 / 2
division_float = 3. / 2.
print(division, division_float)

# for advanced math functions, the library 'math' should be called
import math
exponential = math.exp(3)

### Function

In [ ]:
def compute_power(number, power):
    """
    Compute the power of a number.

    
    -- Arguments--
    number -- Float, the number to be raised at the power 'power'
    power -- Float
    
    
    -- Outputs --
    powered_number -- Float, the result of numberower
    """
    powered_number = number ** power
    return powered_number

In [ ]:
result = compute_power(0.,0.)
print(result)

### Class

In [ ]:
class Power():
    def __init__(self, power):
        """
        
        """
        self.power = power # power is now an attribute of the class Power
    
    def compute_power(self, number):
        """
        Compute the power of a number.
        
        -- Arguments--
        number -- Float, the number to be raised at the power 'power'
        
        -- Outputs --
        powered_number -- Float, the result of numberower
        """
        powered_number = number ** self.power
        return powered_number


In [ ]:
# The object is an instance of the class power
obj_power = Power(power=2)

# Access to method compute_power.
result = obj_power.compute_power(number=3)
print('3^2 = {}'.format(result))


# Check the attribute 'power'
print('power = {}'.format(obj_power.power))

# Modify it
obj_power.power = 3
print('power = {}'.format(obj_power.power))

# NUMPY

In [1]:
# to import numpy with the alias np
import numpy as np

In [ ]:
# now you can call numpy's functions by using np.
# for instance, to create a vector:
vector = np.array([1., -2., 3.5]) # vecteur {1, 2, 3}

In [2]:
matrix2 = np.array([[1, 2], [2, 1]]) # matrix [1, 2 // 2, 1]

matrix3 = np.array([
                    [[1, 2], [1, 2]],
                    [[1, 2], [1, 2]]
                   ]) # matrix 3D

In [4]:
# here are some array generators, you can test them
zero_matrix = np.zeros((3, 3), dtype=float)
linspace_vector = np.linspace(1, 9, 9)
sequence_vector = np.arange(6)
unity_matrix = np.ones((5,5))
identity_matrix = np.eye(5)

# you modify the dimensions of an array
matrix = linspace_vector.reshape(3, 3, order='C')

In [8]:
print(matrix)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [12]:
# access to elements
print('First element of a vector = {}'.format(linspace_vector[0]))                       
print('last element of a vector  = {}'.format(linspace_vector[-1]))                        
print('Two first elements of a vector = {}'.format(linspace_vector[:2]))                       
print('2 by 2 = {}'.format(linspace_vector[::2]))                       
print('From last element = {}'.format(linspace_vector[::-1]))    
print('Element (11) of a matrix = {}'.format(matrix[0, 0]))                       
print('sub-matrix = \n {}'.format( matrix[1:, 1:]))                      
print('another sub-matrix = \n {}'.format(matrix[1:, :]))                       

First element of a vector = 1.0
last element of a vector  = 9.0
Two first elements of a vector = [1. 2.]
2 by 2 = [1. 3. 5. 7. 9.]
From last element = [9. 8. 7. 6. 5. 4. 3. 2. 1.]
Element (11) of a matrix = 1.0
sub-matrix = 
 [[5. 6.]
 [8. 9.]]
another sub-matrix = 
 [[4. 5. 6.]
 [7. 8. 9.]]


In [15]:
# operations
scalar = 5.
vect1 = np.array([0, 1, 2, 3])
vect2 = np.array([[0], [1], [2], [3]])

print('vector1 + scalar = \n {}'.format(vect1 + scalar))
print('vector2 * scalar = \n {}'.format(vect2 * scalar))
print('vector1 + vector2 = \n {}'.format(vect1 + vect2))
print('vector1 * vector2 = \n {}'.format(vect1 * vect2))

vecteur1 + scalaire = 
 [5. 6. 7. 8.]
vecteur2 * scalaire = 
 [[ 0.]
 [ 5.]
 [10.]
 [15.]]
vecteur1 + vecteur2 = 
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
vecteur1 * vecteur2 = 
 [[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [16]:
matrix1 = np.matrix([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
array1 = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
print('matrix1 = \n {}'.format(matrix1))
print('matrix1 * matrix1.T = \n {}'.format(matrix1 * matrix1.T)) # T to transpose
print('matrix1 * matrix1.T = \n {}'.format(np.dot(array1, array1.T)))

matrix1 = 
 [[1 2 3]
 [0 4 5]
 [0 0 6]]
matrix1 * matrix1.T = 
 [[14 23 18]
 [23 41 30]
 [18 30 36]]
matrix1 * matrix1.T = 
 [[14 23 18]
 [23 41 30]
 [18 30 36]]


# PANDAS